[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/images/*"
  to = "/_next/static/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
