-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  role text default 'user'
);

-- Set up Row Level Security (RLS)
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- This trigger automatically creates a profile for new users
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text,
  category text,
  description text,
  is_available boolean default true not null
);

-- Seed initial products
insert into products (name, price, image, category, description) values
('Zone Crop Top - Red Edition', 7500, '/images/products/zone-crop-top-red.jpeg', 'tops', 'Our signature Zone crop top in bold red. Perfect for making a statement at parties and events.'),
('MDMA Streetwear T-Shirt', 8000, '/images/products/mdma-tshirts.jpeg', 't-shirts', 'Bold graphic t-shirt with MDMA print. Perfect for making a statement in the streets of Abuja.'),
('Zone Tube Top - Limited Edition', 6500, '/images/products/zone-crop-top-red2.jpeg', 'tops', 'Limited edition Zone tube top with our iconic logo. Perfect for nights out and making a statement.'),
('Zone Shield T-Shirt', 9000, '/images/products/zone-shield-tshirt.jpeg', 't-shirts', 'Edgy black t-shirt featuring our exclusive Zone shield design with red accents. For those who dare to stand out.'),
('MDMA Striped T-Shirt', 8500, '/images/products/mdma-striped-tshirt.jpeg', 't-shirts', 'Bold black t-shirt with striking red and white MDMA stripes. The perfect statement piece for the urban rebel.');
('6IXSOLDIERS Camo Jersey', 30000, '/images/products/6ixsoldiers-camo-jersey.jpeg', 'jerseys', 'Limited edition camo jersey featuring the exclusive 6IXSOLDIERS design.'),
('6IXSOLDIERS Members Only Shorts', 35000, '/images/products/6ixsoldiers-members-only-shorts.jpeg', 'shorts', 'Exclusive members-only shorts with premium fabric and comfortable fit.'),
('Zone Mules', 80000, '/images/products/zone-mules.jpeg', 'footwear', 'Stylish and comfortable mules featuring the Zone logo.'),
('Convertible Zone Tube Top', 25000, '/images/products/convertible-zone-tube-top.jpeg', 'tops', 'Versatile convertible tube top that can be styled in multiple ways.');
-- Set up RLS for products table
alter table products
  enable row level security;

create policy "Products are viewable by everyone." on products
  for select using (true);

create policy "Admins can update products." on products
  for update to authenticated
  using (
    (select role from profiles where id = auth.uid()) = 'admin'
  )
  with check (
    (select role from profiles where id = auth.uid()) = 'admin'
  );
